"""Centralized VerdictAI error definitions and exception classes."""

from __future__ import annotations

from .definitions import (
    CHUNKER_DOCLING_DEPENDENCIES_UNAVAILABLE,
    CHUNKER_DOCLING_METADATA_INVALID,
    CHUNKER_DOCLING_METADATA_MISSING,
    CHUNKER_OPENAI_TOKENIZER_DEPENDENCY_MISSING,
    CHUNKER_UNSUPPORTED_TOKENIZER_PROVIDER,
    ERROR_DEFINITIONS,
    PARSER_DOCLING_CONVERSION_FAILED,
    PARSER_DOCLING_EMPTY_DOCUMENT,
    PARSER_DOCLING_NO_USABLE_BLOCKS,
    PARSER_DOCLING_NOT_INSTALLED,
    PARSER_PROGRESS_REPORT_MISSING,
    PARSER_RAPIDOCR_NOT_INSTALLED,
    PARSER_SOURCE_NOT_FILE,
    PARSER_SOURCE_NOT_FOUND,
    PARSER_UNSUPPORTED_VLM_PRESET,
    ErrorDefinition,
)
from .exceptions import (
    DoclingChunkerError,
    DoclingParserError,
    VerdictAIError,
    VerdictAIFileNotFoundError,
    VerdictAIRuntimeError,
    VerdictAIValueError,
)

__all__ = [
    "CHUNKER_DOCLING_DEPENDENCIES_UNAVAILABLE",
    "CHUNKER_DOCLING_METADATA_INVALID",
    "CHUNKER_DOCLING_METADATA_MISSING",
    "CHUNKER_OPENAI_TOKENIZER_DEPENDENCY_MISSING",
    "CHUNKER_UNSUPPORTED_TOKENIZER_PROVIDER",
    "ERROR_DEFINITIONS",
    "PARSER_DOCLING_CONVERSION_FAILED",
    "PARSER_DOCLING_EMPTY_DOCUMENT",
    "PARSER_DOCLING_NOT_INSTALLED",
    "PARSER_DOCLING_NO_USABLE_BLOCKS",
    "PARSER_PROGRESS_REPORT_MISSING",
    "PARSER_RAPIDOCR_NOT_INSTALLED",
    "PARSER_SOURCE_NOT_FILE",
    "PARSER_SOURCE_NOT_FOUND",
    "PARSER_UNSUPPORTED_VLM_PRESET",
    "DoclingChunkerError",
    "DoclingParserError",
    "ErrorDefinition",
    "VerdictAIError",
    "VerdictAIFileNotFoundError",
    "VerdictAIRuntimeError",
    "VerdictAIValueError",
]
